language: node_js
services:
  - docker
node_js:
  - "10"
dist: bionic
install:
  - npm install pm2@latest -g
  - npm install
  - cd grpc; npm install; cd $TRAVIS_BUILD_DIR
  - ping -c 3 localhost
script:
  - port=3000 pm2 start app.js --name http
  - curl localhost:3000
  - port=9090 pm2 start grpc/app.js --name grpc
  - port=9090 node grpc/test

