name: pong test

on:
  push:

jobs:
  http:
    env:
      PORT: 3000
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm start
      - run: ping -c 3 localhost
      - run: npm test
  grpc:
    defaults:
      run:
        working-directory: grpc
    runs-on: ubuntu-latest
    env:
      PORT: 9090
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i
      - run: npm start
      - run: ping -c 3 localhost
      - run: npm test