name: TLS pong test

on:
  push:

jobs:
  https:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: https
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm i
      - run: npm start
        env:
          PORT: 3443
      - run: npm run self-signed
        env:
          PORT: 5443
      - run: ping -c 3 localhost
      - run: npm test