# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: test

on:
  push:

jobs:
  http:
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
    env:
      port: 3000
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm start
      - run: npm test
  grpc:
    defaults:
      run:
        working-directory: grpc
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install pm2@latest -g
      - run: npm i
      - run: ping -c 3 localhost
      - run: port=9090 pm2 start app.js --name grpc
      - run: npm test
  https:
    env:
      port: 3443
      fqdn: 140.238.194.116
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: https
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i
      - run: npm start
      - run: npm test