name: pong test

on:
  push:

jobs:
  http:
    defaults:
      run:
        working-directory: http
    env:
      PORT: 3000
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm start
      - run: ping -c 3 localhost
      - run: npm test
  grpc:
    defaults:
      run:
        working-directory: grpc
    runs-on: ubuntu-latest
    env:
      PORT: 9090
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm i
      - run: npm start
      - run: ping -c 3 localhost
      - run: npm test