name: pong test

on:
  push:

jobs:
  http:
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
    env:
      port: 3000
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm start
      - run: npm test
  grpc:
    defaults:
      run:
        working-directory: grpc
    strategy:
      matrix:
        os-version: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install pm2@latest -g
      - run: npm i
      - run: ping -c 3 localhost
      - run: port=9090 pm2 start app.js --name grpc
      - run: npm test