# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: test

on:
  push:
  
jobs:
  http:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install pm2@latest -g
      - run: npm install
      - run: npm test
  grpc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: grpc
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install pm2@latest -g
      - run: npm i
      - run: ping -c 3 localhost
      - run: port=9090 pm2 start app.js --name grpc
      - run: npm test
  https:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: https
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install pm2@latest -g
      - run: npm i
      - run: npm test
